kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/openshift-katacoda/blog-django-py.git'
    deployment.kubernetes.io/revision: '8'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"rm343001-blog-django-py-git:latest","namespace":"rm-343001"},"fieldPath":"spec.template.spec.containers[?(@.name==\"rm343001-blog-django-py-git\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: /apis/apps/v1/namespaces/rm-343001/deployments/rm343001-blog-django-py-git
  resourceVersion: '97926569'
  name: rm343001-blog-django-py-git
  uid: 849beb28-1fdb-4e11-b585-275635acac1b
  creationTimestamp: '2022-07-14T19:59:41Z'
  generation: 8
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2022-07-14T19:59:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"rm343001-blog-django-py-git"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-07-14T20:01:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"rm343001-blog-django-py-git"}':
                  'f:image': {}
    - manager: kubectl-set
      operation: Update
      apiVersion: apps/v1
      time: '2022-07-14T20:41:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"rm343001-blog-django-py-git"}':
                  'f:env':
                    .: {}
                    'k:{"name":"BLOG_BANNER_COLOR"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"BLOG_SITE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DATABASE_URL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2022-07-14T20:41:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
  namespace: rm-343001
  labels:
    app: rm343001-blog-django-py-git
    app.kubernetes.io/component: rm343001-blog-django-py-git
    app.kubernetes.io/instance: rm343001-blog-django-py-git
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: rm343001-blog-django-py-git-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rm343001-blog-django-py-git
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rm343001-blog-django-py-git
        deploymentconfig: rm343001-blog-django-py-git
    spec:
      containers:
        - name: rm343001-blog-django-py-git
          image: >-
            image-registry.openshift-image-registry.svc:5000/rm-343001/rm343001-blog-django-py-git@sha256:1b9473a8ca974c5b3d9159fcf9701ed0a807a6afeb6cca793a8f761e9d3b2a2f
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: BLOG_SITE_NAME
              value: RM-343001
            - name: BLOG_BANNER_COLOR
              value: Green
            - name: DATABASE_URL
              value: 'postgresql://sampledb:sampledb@sample-database:5432/sampledb'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 8
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-07-14T20:01:23Z'
      lastTransitionTime: '2022-07-14T20:01:23Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-07-14T20:41:26Z'
      lastTransitionTime: '2022-07-14T19:59:41Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "rm343001-blog-django-py-git-d8f86487b" has successfully
        progressed.
