kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hpa-rm343001
  namespace: rm-343001
  selfLink: >-
    /apis/autoscaling/v2beta2/namespaces/rm-343001/horizontalpodautoscalers/hpa-rm343001
  uid: d1a3b665-e4cc-455f-a2a7-3b91a4a18a5f
  resourceVersion: '97955268'
  creationTimestamp: '2022-07-14T21:24:46Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2beta2
      time: '2022-07-14T21:24:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v1
      time: '2022-07-14T21:25:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:autoscaling.alpha.kubernetes.io/conditions': {}
            'f:autoscaling.alpha.kubernetes.io/current-metrics': {}
        'f:status':
          'f:currentCPUUtilizationPercentage': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
spec:
  scaleTargetRef:
    kind: Deployment
    name: rm343001-blog-django-py-git
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: '0'
          averageUtilization: 0
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-07-14T21:25:01Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-07-14T21:25:01Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2022-07-14T21:30:01Z'
      reason: TooFewReplicas
      message: the desired replica count is less than the minimum replica count
